/**
 * PostgreSQL storage primitives shared by the app's store driver
 * (`src/lib/db/postgres.ts`) and the copy script
 * (`scripts/db-copy-to-postgres.mjs`).
 *
 * Plain JavaScript typed with JSDoc (like `data-core.mjs`) so the script
 * can import it without a build step. It never imports Prisma: every
 * function takes an executor (`PgExecutor`), which is a PrismaClient or the
 * client of an interactive transaction (`$queryRawUnsafe` /
 * `$executeRawUnsafe`), so the SQL builders are unit tested without a
 * database.
 *
 * Layout (generated by `scripts/prisma-generate-schema.mjs`, see
 * `prisma/schema.prisma` and `postgres-tables.mjs`):
 *  - one table per collection: `id text primary key, doc jsonb, position int,
 *    updated_at timestamptz` plus a real, indexed column per hot key the
 *    document type has (`user_id`, `course_id`, `lesson_id`, `slug`, `email`),
 *    filled from the document by PostgreSQL itself (`doc->>'userId'`) so the
 *    two never disagree. `position` keeps the array order;
 *  - `settings`: a single row (`id = 1`) holding the settings JSON;
 *  - `meta`: key/value pairs (`initialized_at`, `initialized_from`,
 *    `write_seq`, …). Every write transaction first bumps `write_seq`, which
 *    serializes writers and tells a process that someone else wrote.
 *
 * SQL is never built from data: identifiers come from the generated table
 * map (and are validated), every value travels as a parameter. A batch of
 * documents is one `jsonb` parameter unpacked with `jsonb_to_recordset`.
 */
import { PG_TABLES } from "./postgres-tables.mjs";

/**
 * @typedef {object} PgExecutor
 * @property {(sql: string, ...values: unknown[]) => Promise<unknown>} $queryRawUnsafe
 * @property {(sql: string, ...values: unknown[]) => Promise<number>} $executeRawUnsafe
 */
/** @typedef {{ table: string; columns: { key: string; column: string }[] }} TableSpec */
/** @typedef {import("./data-core.mjs").RawData} RawData */
/** @typedef {import("./data-core.mjs").ChangeSet} ChangeSet */
/** @typedef {{ sql: string; params: unknown[] }} Statement */

/** Rows per INSERT statement (one jsonb parameter each). */
export const BATCH_ROWS = 1000;
/** Approximate payload bytes per INSERT statement. */
export const BATCH_BYTES = 4 * 1024 * 1024;
/** Rows read per page when loading a table. */
export const PAGE_ROWS = 5000;
/** Ids per DELETE / reorder statement. */
export const ID_BATCH = 10_000;

const IDENT = /^[a-z_][a-z0-9_]{0,62}$/;
const DOC_KEY = /^[A-Za-z][A-Za-z0-9]{0,62}$/;

/** A validated, quoted identifier. */
export function quoteIdent(/** @type {string} */ name) {
  if (!IDENT.test(name)) throw new Error(`"${name}" is not a valid table or column name.`);
  return `"${name}"`;
}

/**
 * The table of a collection.
 * @param {string} name
 * @param {Readonly<Record<string, TableSpec>>} [tables]
 * @returns {TableSpec}
 */
export function tableFor(name, tables = PG_TABLES) {
  const spec = Object.hasOwn(tables, name) ? tables[name] : undefined;
  if (!spec) throw new Error(`The PostgreSQL schema has no table for the collection "${name}". Run "npm run prisma:schema" and "npm run db:setup".`);
  return spec;
}

/** Names of the collections the schema has a table for. */
export function knownCollections(tables = PG_TABLES) {
  return Object.keys(tables);
}

/**
 * PostgreSQL cannot store the NUL character in text or jsonb: replace every
 * `\u0000` escape in a JSON text by U+FFFD. Escaped backslashes followed by
 * "u0000" (the text `\u0000` typed by someone) are left alone.
 */
export function sanitizeJson(/** @type {string} */ json) {
  if (!json.includes("\\u0000")) return json;
  return json.replace(/(?<!\\)((?:\\\\)*)\\u0000/g, "$1\\ufffd");
}

/**
 * The values of the extracted columns for one document, as PostgreSQL
 * stores them (`doc->>'key'`): strings as they are, other scalars as their
 * JSON text, missing or null values as null. Used by tests and checks; the
 * SQL computes the same values itself.
 * @param {TableSpec} spec
 * @param {unknown} doc
 * @returns {Record<string, string | null>}
 */
export function extractColumns(spec, doc) {
  /** @type {Record<string, string | null>} */
  const out = {};
  const source = doc && typeof doc === "object" ? /** @type {Record<string, unknown>} */ (doc) : {};
  for (const { key, column } of spec.columns) {
    const value = source[key];
    out[column] = value === undefined || value === null ? null : typeof value === "string" ? value : JSON.stringify(value);
  }
  return out;
}

/** `doc->>'userId'` for each extracted column (keys come from the generated map and are validated). */
function columnExpressions(/** @type {TableSpec} */ spec, /** @type {string} */ alias) {
  return spec.columns.map(({ key }) => {
    if (!DOC_KEY.test(key)) throw new Error(`"${key}" cannot be an extracted document key.`);
    return `${alias}.doc->>'${key}'`;
  });
}

/**
 * Split rows (`{ id, json }`) into batches of at most `maxRows` rows and
 * about `maxBytes` of JSON each (a single larger row gets its own batch).
 *
 * @template {{ id: string; json: string }} R
 * @param {readonly R[]} rows
 * @param {{ maxRows?: number; maxBytes?: number }} [limits]
 * @returns {R[][]}
 */
export function batchRows(rows, limits = {}) {
  const maxRows = Math.max(1, limits.maxRows ?? BATCH_ROWS);
  const maxBytes = Math.max(1, limits.maxBytes ?? BATCH_BYTES);
  /** @type {R[][]} */
  const out = [];
  /** @type {R[]} */
  let current = [];
  let bytes = 0;
  for (const row of rows) {
    const size = row.json.length + row.id.length + 32;
    if (current.length && (current.length >= maxRows || bytes + size > maxBytes)) {
      out.push(current);
      current = [];
      bytes = 0;
    }
    current.push(row);
    bytes += size;
  }
  if (current.length) out.push(current);
  return out;
}

/**
 * Split a list into chunks of `size`.
 * @template T
 * @param {readonly T[]} items
 * @param {number} [size]
 * @returns {T[][]}
 */
export function chunk(items, size = ID_BATCH) {
  /** @type {T[][]} */
  const out = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}

/** The jsonb payload of a batch: `[{"id":…,"ord":n,"doc":{…}}, …]` (each `json` is already valid JSON). */
export function batchPayload(/** @type {readonly { id: string; json: string }[]} */ rows, firstOrd = 0) {
  let out = "[";
  rows.forEach((row, i) => {
    if (i) out += ",";
    out += `{"id":${JSON.stringify(row.id)},"ord":${firstOrd + i},"doc":${sanitizeJson(row.json)}}`;
  });
  return `${out}]`;
}

/**
 * Upsert one batch of documents. Existing rows keep their position; new
 * rows are placed after every existing one, in batch order (like an
 * append to the array). The extracted columns are recomputed from the new document.
 *
 * @param {TableSpec} spec
 * @param {readonly { id: string; json: string }[]} rows  Distinct ids.
 * @param {string} now  ISO timestamp.
 * @returns {Statement}
 */
export function upsertStatement(spec, rows, now) {
  const t = quoteIdent(spec.table);
  const extra = spec.columns.map((c) => quoteIdent(c.column));
  const insertColumns = ['"id"', '"doc"', '"position"', '"updated_at"', ...extra].join(", ");
  const values = ["r.id", "r.doc", "(SELECT COALESCE(MAX(t.position), -1) FROM " + t + " t) + COALESCE(n.k, 0)", "$2::timestamptz", ...columnExpressions(spec, "r")].join(", ");
  const updates = ['"doc" = EXCLUDED."doc"', '"updated_at" = EXCLUDED."updated_at"', ...extra.map((c) => `${c} = EXCLUDED.${c}`)].join(", ");
  const sql =
    `WITH r AS (SELECT * FROM jsonb_to_recordset($1::jsonb) AS x(id text, ord int, doc jsonb)), ` +
    `n AS (SELECT r.id, row_number() OVER (ORDER BY r.ord) AS k FROM r WHERE NOT EXISTS (SELECT 1 FROM ${t} e WHERE e.id = r.id)) ` +
    `INSERT INTO ${t} (${insertColumns}) SELECT ${values} FROM r LEFT JOIN n ON n.id = r.id ORDER BY r.ord ` +
    `ON CONFLICT ("id") DO UPDATE SET ${updates}`;
  return { sql, params: [batchPayload(rows), now] };
}

/**
 * Insert one batch into an emptied table at positions `firstOrd…` (replacing
 * everything). Ids repeated in the same batch or an earlier one are skipped.
 *
 * @param {TableSpec} spec
 * @param {readonly { id: string; json: string }[]} rows
 * @param {number} firstOrd
 * @param {string} now
 * @returns {Statement}
 */
export function insertStatement(spec, rows, firstOrd, now) {
  const t = quoteIdent(spec.table);
  const extra = spec.columns.map((c) => quoteIdent(c.column));
  const insertColumns = ['"id"', '"doc"', '"position"', '"updated_at"', ...extra].join(", ");
  const values = ["r.id", "r.doc", "r.ord", "$2::timestamptz", ...columnExpressions(spec, "r")].join(", ");
  const sql =
    `INSERT INTO ${t} (${insertColumns}) SELECT ${values} FROM jsonb_to_recordset($1::jsonb) AS r(id text, ord int, doc jsonb) ` +
    `ORDER BY r.ord ON CONFLICT ("id") DO NOTHING`;
  return { sql, params: [batchPayload(rows, firstOrd), now] };
}

/** Delete ids (one statement per `ID_BATCH`). @returns {Statement[]} */
export function deleteStatements(/** @type {TableSpec} */ spec, /** @type {readonly string[]} */ ids) {
  const t = quoteIdent(spec.table);
  return chunk(ids).map((part) => ({ sql: `DELETE FROM ${t} WHERE "id" IN (SELECT jsonb_array_elements_text($1::jsonb))`, params: [JSON.stringify(part)] }));
}

/** Renumber rows so that `ids` (every id, in array order) get positions 0…n-1. @returns {Statement[]} */
export function reorderStatements(/** @type {TableSpec} */ spec, /** @type {readonly string[]} */ ids) {
  const t = quoteIdent(spec.table);
  return chunk(ids).map((part, index) => ({
    sql: `UPDATE ${t} AS t SET "position" = r.ord::int - 1 + $2::int FROM jsonb_array_elements_text($1::jsonb) WITH ORDINALITY AS r(id, ord) WHERE t."id" = r.id`,
    params: [JSON.stringify(part), index * ID_BATCH],
  }));
}

/** @returns {Statement} */
export function settingsStatement(/** @type {string} */ json, /** @type {string} */ now) {
  return {
    sql: `INSERT INTO "settings" ("id", "data", "updated_at") VALUES (1, $1::jsonb, $2::timestamptz) ON CONFLICT ("id") DO UPDATE SET "data" = EXCLUDED."data", "updated_at" = EXCLUDED."updated_at"`,
    params: [sanitizeJson(json), now],
  };
}

/** @returns {Statement} */
export function setMetaStatement(/** @type {string} */ key, /** @type {string} */ value) {
  return { sql: `INSERT INTO "meta" ("key", "value") VALUES ($1, $2) ON CONFLICT ("key") DO UPDATE SET "value" = EXCLUDED."value"`, params: [key, value] };
}

/** Bump `write_seq` (taking the row lock that serializes writers); returns the new value. */
export const BUMP_SEQ_SQL = `INSERT INTO "meta" ("key", "value") VALUES ('write_seq', '1') ON CONFLICT ("key") DO UPDATE SET "value" = (("meta"."value")::bigint + 1)::text RETURNING "value"`;

/**
 * Every statement a change set needs, in order: per collection upserts,
 * deletes, then the renumbering; the settings last. (`write_seq` is bumped
 * separately, first.)
 *
 * @param {ChangeSet} changes
 * @param {string} now
 * @param {{ tables?: Readonly<Record<string, TableSpec>>; maxRows?: number; maxBytes?: number }} [options]
 * @returns {Statement[]}
 */
export function changeSetStatements(changes, now, options = {}) {
  /** @type {Statement[]} */
  const out = [];
  for (const change of changes.collections) {
    const spec = tableFor(change.name, options.tables);
    for (const rows of batchRows(change.upserts, options)) out.push(upsertStatement(spec, rows, now));
    if (change.deletes.length) out.push(...deleteStatements(spec, change.deletes));
    if (change.order?.length) out.push(...reorderStatements(spec, change.order));
  }
  if (changes.settings !== null) out.push(settingsStatement(changes.settings, now));
  return out;
}

/** The id of a document, or null. */
function docId(/** @type {unknown} */ doc) {
  if (!doc || typeof doc !== "object") return null;
  const id = /** @type {{ id?: unknown }} */ (doc).id;
  return typeof id === "string" && id.length > 0 ? id : null;
}

/**
 * Statements that replace a whole table with `docs` (array order kept;
 * repeated ids keep their first copy).
 *
 * @param {string} name
 * @param {readonly unknown[]} docs
 * @param {string} now
 * @param {{ tables?: Readonly<Record<string, TableSpec>>; maxRows?: number; maxBytes?: number }} [options]
 * @returns {{ statements: Statement[]; stored: number; duplicates: number }}
 */
export function replaceTableStatements(name, docs, now, options = {}) {
  const spec = tableFor(name, options.tables);
  /** @type {Statement[]} */
  const statements = [{ sql: `DELETE FROM ${quoteIdent(spec.table)}`, params: [] }];
  const seen = new Set();
  /** @type {{ id: string; json: string }[]} */
  const rows = [];
  let duplicates = 0;
  docs.forEach((doc, index) => {
    const id = docId(doc);
    if (!id) throw new Error(`Collection "${name}", item ${index + 1} has no id.`);
    if (seen.has(id)) {
      duplicates++;
      return;
    }
    seen.add(id);
    rows.push({ id, json: JSON.stringify(doc) });
  });
  let ord = 0;
  for (const batch of batchRows(rows, options)) {
    statements.push(insertStatement(spec, batch, ord, now));
    ord += batch.length;
  }
  return { statements, stored: rows.length, duplicates };
}

/* ------------------------------------------------------------------ */
/* Running statements                                                  */
/* ------------------------------------------------------------------ */

/** @param {PgExecutor} db @param {Statement} statement */
export function run(db, statement) {
  return db.$executeRawUnsafe(statement.sql, ...statement.params);
}

/**
 * @template [T=Record<string, unknown>]
 * @param {PgExecutor} db
 * @param {string} sql
 * @param {unknown[]} [params]
 * @returns {Promise<T[]>}
 */
export async function query(db, sql, params = []) {
  return /** @type {T[]} */ (await db.$queryRawUnsafe(sql, ...params));
}

/** Bump `write_seq` and return the new value (call first in every write transaction). */
export async function bumpWriteSeq(/** @type {PgExecutor} */ db) {
  const rows = await query(db, BUMP_SEQ_SQL);
  return Number(rows[0]?.value ?? 0);
}

/** The current `write_seq` (0 before the first write). */
export async function readWriteSeq(/** @type {PgExecutor} */ db) {
  const rows = await query(db, `SELECT "value" FROM "meta" WHERE "key" = 'write_seq'`);
  return Number(rows[0]?.value ?? 0);
}

/** Apply a change set (inside a transaction that already bumped `write_seq`). */
export async function applyChangeSet(/** @type {PgExecutor} */ db, /** @type {ChangeSet} */ changes, now = new Date().toISOString(), options = {}) {
  for (const statement of changeSetStatements(changes, now, options)) await run(db, statement);
}

/** All meta rows. */
export async function readMeta(/** @type {PgExecutor} */ db) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const row of await query(db, `SELECT "key", "value" FROM "meta" ORDER BY "key"`)) out[String(row.key)] = String(row.value);
  return out;
}

/** Tables of the current schema. */
export async function listTables(/** @type {PgExecutor} */ db) {
  const rows = await query(db, `SELECT table_name FROM information_schema.tables WHERE table_schema = current_schema() AND table_type = 'BASE TABLE'`);
  return new Set(rows.map((row) => String(row.table_name)));
}

/**
 * Collections (of `names`) whose table is missing, plus missing
 * `settings`/`meta`: the schema has not been migrated.
 */
export async function missingTables(/** @type {PgExecutor} */ db, /** @type {readonly string[]} */ names, tables = PG_TABLES) {
  const present = await listTables(db);
  const missing = ["settings", "meta"].filter((t) => !present.has(t));
  for (const name of names) {
    const spec = Object.hasOwn(tables, name) ? tables[name] : undefined;
    if (!spec || !present.has(spec.table)) missing.push(spec ? spec.table : name);
  }
  return missing;
}

/** Whether the database already holds the site (imported, seeded or restored). */
export async function isInitialized(/** @type {PgExecutor} */ db) {
  const rows = await query(db, `SELECT (EXISTS (SELECT 1 FROM "meta" WHERE "key" = 'initialized_at') OR EXISTS (SELECT 1 FROM "settings" WHERE "id" = 1)) AS "found"`);
  return rows[0]?.found === true;
}

/** Row counts per collection (one statement). */
export async function countRows(/** @type {PgExecutor} */ db, /** @type {readonly string[]} */ names, tables = PG_TABLES) {
  /** @type {Record<string, number>} */
  const counts = {};
  if (!names.length) return counts;
  const parts = names.map((name, i) => `SELECT ${i} AS "i", count(*)::int AS "n" FROM ${quoteIdent(tableFor(name, tables).table)}`);
  for (const row of await query(db, parts.join(" UNION ALL "))) counts[names[Number(row.i)]] = Number(row.n);
  return counts;
}

/**
 * Read every document of `names` (in position order, a page at a time) and
 * the settings. Run it inside a REPEATABLE READ transaction for a
 * consistent snapshot.
 *
 * @param {PgExecutor} db
 * @param {readonly string[]} names
 * @param {{ tables?: Readonly<Record<string, TableSpec>>; pageRows?: number }} [options]
 * @returns {Promise<RawData>}
 */
export async function readAllData(db, names, options = {}) {
  const pageRows = Math.max(1, Math.floor(options.pageRows ?? PAGE_ROWS));
  /** @type {Record<string, unknown[]>} */
  const collections = {};
  for (const name of names) {
    const t = quoteIdent(tableFor(name, options.tables).table);
    /** @type {unknown[]} */
    const docs = [];
    /** @type {{ position: number; id: string } | null} */
    let last = null;
    for (;;) {
      /** @type {Record<string, unknown>[]} */
      const rows = last
        ? await query(db, `SELECT "id", "position", "doc"::text AS "doc" FROM ${t} WHERE ("position", "id") > ($1::int, $2::text) ORDER BY "position", "id" LIMIT ${pageRows}`, [
            last.position,
            last.id,
          ])
        : await query(db, `SELECT "id", "position", "doc"::text AS "doc" FROM ${t} ORDER BY "position", "id" LIMIT ${pageRows}`);
      for (const row of rows) {
        try {
          docs.push(JSON.parse(String(row.doc)));
        } catch {
          throw new Error(`Collection "${name}" has a damaged document (id ${String(row.id)}): it is not valid JSON.`);
        }
      }
      if (rows.length < pageRows) break;
      const tail = rows[rows.length - 1];
      last = { position: Number(tail.position), id: String(tail.id) };
    }
    collections[name] = docs;
  }
  const settingsRows = await query(db, `SELECT "data"::text AS "data" FROM "settings" WHERE "id" = 1`);
  const settings = settingsRows.length ? JSON.parse(String(settingsRows[0].data)) : null;
  return { collections, settings };
}

/**
 * Replace everything with `data` (inside a transaction that already bumped
 * `write_seq`): every collection of `names` ends up holding exactly the
 * documents of `data`. Collections of `data` without a table are not
 * stored and are returned in `skipped`.
 *
 * With `initialize`, nothing is written when the database already holds a
 * site (another process got there first) and `written` is false.
 *
 * @param {PgExecutor} db
 * @param {RawData} data
 * @param {readonly string[]} names
 * @param {{ source?: string; initialize?: boolean; tables?: Readonly<Record<string, TableSpec>>; now?: string }} [options]
 */
export async function writeAllData(db, data, names, options = {}) {
  const now = options.now ?? new Date().toISOString();
  if (options.initialize && (await isInitialized(db))) return { written: false, skipped: /** @type {string[]} */ ([]), duplicates: /** @type {Record<string, number>} */ ({}) };
  const tables = options.tables ?? PG_TABLES;
  const skipped = Object.keys(data.collections).filter((name) => !Object.hasOwn(tables, name) && (data.collections[name]?.length ?? 0) > 0);
  /** @type {Record<string, number>} */
  const duplicates = {};
  for (const name of names) {
    const result = replaceTableStatements(name, data.collections[name] ?? [], now, { tables });
    if (result.duplicates) duplicates[name] = result.duplicates;
    for (const statement of result.statements) await run(db, statement);
  }
  if (data.settings && typeof data.settings === "object") await run(db, settingsStatement(JSON.stringify(data.settings), now));
  else await run(db, { sql: `DELETE FROM "settings"`, params: [] });
  const meta = await readMeta(db);
  if (!meta.initialized_at) {
    await run(db, setMetaStatement("initialized_at", now));
    if (options.source) await run(db, setMetaStatement("initialized_from", options.source));
  } else if (options.source) {
    await run(db, setMetaStatement("last_replaced_at", now));
    await run(db, setMetaStatement("last_replaced_from", options.source));
  }
  return { written: true, skipped, duplicates };
}

/** Documents per collection a full copy must store: distinct ids, collections with a table only. */
export function expectedCounts(/** @type {RawData} */ data, /** @type {readonly string[]} */ names) {
  /** @type {Record<string, number>} */
  const counts = {};
  for (const name of names) {
    const ids = new Set();
    for (const doc of data.collections[name] ?? []) ids.add(/** @type {{ id: string }} */ (doc).id);
    counts[name] = ids.size;
  }
  return counts;
}

/** Collections whose stored count differs from the expected one. */
export function countMismatches(/** @type {Record<string, number>} */ expected, /** @type {Record<string, number>} */ actual) {
  return Object.keys(expected)
    .filter((name) => (actual[name] ?? 0) !== expected[name])
    .map((name) => `${name}: expected ${expected[name]}, stored ${actual[name] ?? 0}`);
}

/**
 * The connection target of a PostgreSQL URL without credentials or
 * secrets, for logs and the admin page: `postgresql://host:port/db?schema=x`.
 */
export function describeDatabaseUrl(/** @type {string} */ url) {
  try {
    const parsed = new URL(url);
    const schema = parsed.searchParams.get("schema");
    return `${parsed.protocol}//${parsed.hostname}${parsed.port ? `:${parsed.port}` : ""}${parsed.pathname}${schema ? `?schema=${schema}` : ""}`;
  } catch {
    return "postgresql://(invalid DATABASE_URL)";
  }
}
